### ISSUE TITLE
Quick concerns

### ISSUE THREAD

**Issue by RohanAlexander** [karenrni/Forecasting-the-2024-US-Presidential-Elections#1]
- README not updated
- Testing was limited.
- Remove files/folders that you're not using
- Add main result into subtitle.
- Fix "Post, The Washington", by using double braces around The Washington Post in your bibtex file e.g. {{The Washington Post}}
- R not cited.
- Data not cited.
- Sketches not done.

**Comment by karenrni** [comment]
README not updated
Testing was limited.
~~Remove files/folders that you're not using~~
Add main result into subtitle.
~~Fix "Post, The Washington", by using double braces around The Washington Post in your bibtex file e.g. {{The Washington Post}}~~
~~R not cited.~~
~~Data not cited.~~
Sketches not done.
It doesn't make sense to load both tidyverse and dplyr.
close this issue

**Comment by karenrni** [comment]
done
